"""Remove provinsi and tipe_sekolah

Revision ID: 10e40813414d
Revises: 6e7e500c512d
Create Date: 2026-06-19 01:07:31.767521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e40813414d'
down_revision = '6e7e500c512d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('tipe_sekolah')
        batch_op.drop_column('provinsi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provinsi', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('tipe_sekolah', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
