"""drop item_feedback and add foreign keys with cascade

Revision ID: 2e566de2816e
Revises: a1b2c3d4e5f6
Create Date: 2026-06-21 23:59:20.681455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e566de2816e'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # === CLEANUP ORPHAN DATA ===
    op.execute("DELETE FROM question_responses WHERE session_id NOT IN (SELECT session_id FROM user_profiles)")
    op.execute("DELETE FROM recommendation_results WHERE session_id NOT IN (SELECT session_id FROM user_profiles)")
    op.execute("DELETE FROM recommendation_feedback WHERE session_id NOT IN (SELECT session_id FROM user_profiles)")
    op.execute("DELETE FROM session_evaluations WHERE session_id NOT IN (SELECT session_id FROM user_profiles)")
    op.execute("DELETE FROM feedback_sessions WHERE session_id NOT IN (SELECT session_id FROM user_profiles)")
    # ===========================
    with op.batch_alter_table('item_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_feedback_feedback'))
        batch_op.drop_index(batch_op.f('ix_item_feedback_session_id'))

    op.drop_table('item_feedback')
    with op.batch_alter_table('feedback_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user_profiles', ['session_id'], ['session_id'], ondelete='CASCADE')

    with op.batch_alter_table('question_responses', schema=None) as batch_op:
        batch_op.create_index('ix_question_responses_session_question', ['session_id', 'question_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_profiles', ['session_id'], ['session_id'], ondelete='CASCADE')

    with op.batch_alter_table('recommendation_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_recommendation_feedback_session_jurusan', ['session_id', 'jurusan'], unique=False)
        batch_op.create_foreign_key(None, 'user_profiles', ['session_id'], ['session_id'], ondelete='CASCADE')

    with op.batch_alter_table('recommendation_results', schema=None) as batch_op:
        batch_op.create_index('ix_recommendation_results_jurusan', ['jurusan'], unique=False)
        batch_op.create_foreign_key(None, 'user_profiles', ['session_id'], ['session_id'], ondelete='CASCADE')

    with op.batch_alter_table('session_evaluations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user_profiles', ['session_id'], ['session_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('recommendation_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_recommendation_results_jurusan')

    with op.batch_alter_table('recommendation_feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_recommendation_feedback_session_jurusan')

    with op.batch_alter_table('question_responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_question_responses_session_question')

    with op.batch_alter_table('feedback_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('item_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('rekomendasi_jurusan', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('item_feedback_pkey'))
    )
    with op.batch_alter_table('item_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_feedback_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_feedback_feedback'), ['feedback'], unique=False)

    # ### end Alembic commands ###
