"""add web feedback fields

Revision ID: 622e2baf89ec
Revises: 
Create Date: 2026-06-15 17:46:40.087938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622e2baf89ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Check feedback_sessions columns
    columns_fs = [c['name'] for c in inspector.get_columns('feedback_sessions')]
    with op.batch_alter_table('feedback_sessions', schema=None) as batch_op:
        if 'web_rating' not in columns_fs:
            batch_op.add_column(sa.Column('web_rating', sa.Integer(), nullable=True))
        if 'web_komentar' not in columns_fs:
            batch_op.add_column(sa.Column('web_komentar', sa.Text(), nullable=True))

    # Check item_feedback indexes
    indexes_if = [idx['name'] for idx in inspector.get_indexes('item_feedback')]
    with op.batch_alter_table('item_feedback', schema=None) as batch_op:
        if 'ix_item_feedback_feedback' not in indexes_if:
            batch_op.create_index(batch_op.f('ix_item_feedback_feedback'), ['feedback'], unique=False)
        if 'ix_item_feedback_session_id' not in indexes_if:
            batch_op.create_index(batch_op.f('ix_item_feedback_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_feedback_session_id'))
        batch_op.drop_index(batch_op.f('ix_item_feedback_feedback'))

    with op.batch_alter_table('feedback_sessions', schema=None) as batch_op:
        batch_op.drop_column('web_komentar')
        batch_op.drop_column('web_rating')

    # ### end Alembic commands ###
