"""add disliked_tags and swipe_history to feedback_sessions

Revision ID: 6e7e500c512d
Revises: 622e2baf89ec
Create Date: 2026-06-16 08:14:20.823744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7e500c512d'
down_revision = '622e2baf89ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disliked_tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('swipe_history', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_sessions', schema=None) as batch_op:
        batch_op.drop_column('swipe_history')
        batch_op.drop_column('disliked_tags')

    # ### end Alembic commands ###
