"""Drop feedback_sessions completely and add nama to user_profiles

Revision ID: be8582afd648
Revises: d6f03ece2248
Create Date: 2026-06-22 00:24:21.948004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be8582afd648'
down_revision = 'd6f03ece2248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_sessions_timestamp'))

    op.drop_table('feedback_sessions')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('nama')

    op.create_table('feedback_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('komentar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('web_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('web_komentar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_profiles.session_id'], name=op.f('feedback_sessions_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_sessions_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('feedback_sessions_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('feedback_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_sessions_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###
