"""Simplify FeedbackSession redundant columns

Revision ID: d6f03ece2248
Revises: 2e566de2816e
Create Date: 2026-06-22 00:13:31.882196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f03ece2248'
down_revision = '2e566de2816e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_sessions', schema=None) as batch_op:
        batch_op.drop_column('liked_tags')
        batch_op.drop_column('hasil_3')
        batch_op.drop_column('swipe_history')
        batch_op.drop_column('hasil_1')
        batch_op.drop_column('hasil_2')
        batch_op.drop_column('disliked_tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disliked_tags', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hasil_2', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hasil_1', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('swipe_history', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hasil_3', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('liked_tags', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
